# Generated by Django 6.0.5 on 2026-09-28 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_options_post_login_required_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='login_required',
            new_name='login_require',
        ),
    ]
